Testing guide for Canis Major blockchain adaptor
FIWARE/CanisMajor pull request #93
Opened 2024-12-19 15:19 UTC by asmataamallah25

This document provides a comprehensive guide for testing the Canis Major blockchain adaptor's functionality.

2024-12-19 16:39 UTC, flopezag requested changes

2024-12-19 16:39 UTC, flopezag commented on validator/README.md
> + - These data are authenticated through a PEP Proxy and KeyRock Identity Management.
It is not clear to me why we have this comment. All the examples developed does not include Keyrock in the transactions. Can you elaborate it?

2024-12-19 16:39 UTC, flopezag commented on validator/README.md
> + ### Integradtion tests
Integration tests

2024-12-19 16:39 UTC, flopezag commented on validator/README.md
> +    docker-compose -f docker-compose/docker-compose-env.yaml -f docker-compose/docker-compose-java.yaml up
Not sure if you execute this command, it is possible to execute the next command... Can you check it?

2024-12-19 16:39 UTC, flopezag commented on validator/README.md
> +- Wallet-Address: Points to the Ethereum accoun
account

You need to explain the reason for those values regarding Wallet HTTP Headers

2024-12-19 16:39 UTC, flopezag commented on validator/README.md
> +##### Wallet Headers
Wallet HTTP Headers

2024-12-19 16:39 UTC, flopezag commented on validator/README.md
> +{
please, split the response of the JSON properties in different lines, to help to read them. You can use `jq` to help with it.

2024-12-19 16:39 UTC, flopezag commented on validator/README.md
> +The @context is using a definition on smart data models for a DLTtxReceipt and the NGSILD-Tenant is defined in the start-up of the tests.
The @context is using a definition on smart data models for a DLTtxReceipt and the NGSILD-Tenant is defined in the start-up of the tests.

I do not understand this sentence, are you making reference to the Header content or to the response content?

2024-12-19 16:39 UTC, flopezag commented on validator/README.md
> +To retrieve detailed receipt information for a specific building from the Canis Major, use the following HTTP request:
for a specific building entity

2024-12-19 16:39 UTC, flopezag commented on validator/README.md
> +To retrieve specific DLT transaction receipts from the the context broker, we'll use an NGSI-LD query that filters entities by type and property values. The query targets entities of type DLTtxReceip
The `attrs=TxReceipts`

`TxReceipts`

`urn:ngsi-ld:Building:warehouse001`

2024-12-19 16:39 UTC, flopezag commented on validator/README.md
> +
The last description of the comparison between the two (Canis Major and CB) is missing. Just to show that the values are the same.

2024-12-19 16:39 UTC, flopezag commented on validator/ValidationService.java
> +    }
I assume that it is a draft of the operation as it is now

2024-12-19 16:39 UTC, flopezag commented on validator/client/ValidationHttpClient.java
> +}
add a new line at the end of the file

2024-12-19 16:39 UTC, flopezag commented on validator/controller/ValidationController.java
> +@RequestMapping("/validation service")
"/validation service"?

how do you call this endpoint?

2024-12-19 16:39 UTC, flopezag commented on validator/controller/ValidationController.java
> +}
Please, take a look to the diagram that I sent to you about the endpoints to be implemented.

Add a new line at the end of the file.

2024-12-19 16:39 UTC, flopezag commented on validator/model/ValidationInfo.java
> +}
Add a new line at the end of the file

2024-12-19 16:39 UTC, flopezag commented on validator/model/ValidationResult.java
> +}
Add a new line at the end of the file

2025-01-06 16:01 UTC, asmataamallah25 commented on validator/README.md
> +To retrieve detailed receipt information for a specific building from the Canis Major, use the following HTTP request:
Done

2025-01-06 16:02 UTC, asmataamallah25 commented on validator/README.md
> +##### Wallet Headers
Done

2025-01-06 16:02 UTC, asmataamallah25 commented on validator/README.md
> +- Wallet-Address: Points to the Ethereum accoun
Done

2025-01-06 16:02 UTC, asmataamallah25 commented on validator/README.md
> +    docker-compose -f docker-compose/docker-compose-env.yaml -f docker-compose/docker-compose-java.yaml up
This command is the same from the master branch, because you need to access the it folder where you find the docker compose files to run

2025-01-06 16:03 UTC, asmataamallah25 commented on validator/README.md
> + ### Integradtion tests
Done

2025-01-06 16:03 UTC, asmataamallah25 commented on validator/README.md
> +{
I already used the jq, I will try to make look better.

2025-01-06 16:04 UTC, asmataamallah25 commented on validator/README.md
> +The @context is using a definition on smart data models for a DLTtxReceipt and the NGSILD-Tenant is defined in the start-up of the tests.
I am making reference to the Header content

2025-01-06 16:05 UTC, asmataamallah25 commented on validator/README.md
> +
I can not do more in this part, because it will be handled by the validation service itself. I tried my best to make a quick comparison at this level until the validation service is ready. I can remove this part of you want.

2025-01-06 16:06 UTC, asmataamallah25 commented on validator/ValidationService.java
> +    }
Yes, it was. Now I am enhancing the code. I solved all the errors I had and made huge modifications.

2025-01-14 09:15 UTC, closed without merging